// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolManager.Data;

#nullable disable

namespace SchoolManager.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260209231531_enrollmentEntities")]
    partial class enrollmentEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchoolManager.Models.preenrollment_addresses", b =>
                {
                    b.Property<int>("IdAddress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAddress"));

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("exterior_number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("id_data")
                        .HasColumnType("int");

                    b.Property<string>("interior_number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("neighborhood")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("postal_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("state")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAddress");

                    b.HasIndex("id_data");

                    b.ToTable("preenrollment_addresses");
                });

            modelBuilder.Entity("SchoolManager.Models.preenrollment_careers", b =>
                {
                    b.Property<int>("IdCareer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCareer"));

                    b.Property<string>("name_career")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCareer");

                    b.ToTable("preenrollment_careers");
                });

            modelBuilder.Entity("SchoolManager.Models.preenrollment_general", b =>
                {
                    b.Property<int>("IdData")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdData"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Curp")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("IdCareer")
                        .HasColumnType("int");

                    b.Property<string>("MaternalLastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PaternalLastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdData");

                    b.HasIndex("Curp")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdCareer");

                    b.ToTable("preenrollment_general");
                });

            modelBuilder.Entity("SchoolManager.Models.preenrollment_infos", b =>
                {
                    b.Property<int>("IdInfo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInfo"));

                    b.Property<string>("beca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("comu_indi")
                        .HasColumnType("bit");

                    b.Property<bool>("disease")
                        .HasColumnType("bit");

                    b.Property<int>("id_data")
                        .HasColumnType("int");

                    b.Property<bool>("incapa")
                        .HasColumnType("bit");

                    b.Property<bool>("lengu_indi")
                        .HasColumnType("bit");

                    b.HasKey("IdInfo");

                    b.HasIndex("id_data");

                    b.ToTable("preenrollment_infos");
                });

            modelBuilder.Entity("SchoolManager.Models.preenrollment_schools", b =>
                {
                    b.Property<int>("IdSchool")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSchool"));

                    b.Property<decimal>("average")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("degree")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("end_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("high_school_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("id_data")
                        .HasColumnType("int");

                    b.Property<string>("school")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("start_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("state")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("study_system")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSchool");

                    b.HasIndex("id_data");

                    b.ToTable("preenrollment_schools");
                });

            modelBuilder.Entity("SchoolManager.Models.preenrollment_tutors", b =>
                {
                    b.Property<int>("IdTutor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTutor"));

                    b.Property<string>("home_phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("id_data")
                        .HasColumnType("int");

                    b.Property<string>("maternal_last_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("paternal_last_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("relationship")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("work_phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTutor");

                    b.HasIndex("id_data");

                    b.ToTable("preenrollment_tutors");
                });

            modelBuilder.Entity("SchoolManager.Models.preenrollment_addresses", b =>
                {
                    b.HasOne("SchoolManager.Models.preenrollment_general", "preenrollment_general")
                        .WithMany("Addresses")
                        .HasForeignKey("id_data")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("preenrollment_general");
                });

            modelBuilder.Entity("SchoolManager.Models.preenrollment_general", b =>
                {
                    b.HasOne("SchoolManager.Models.preenrollment_careers", "Career")
                        .WithMany("preenrollment_general")
                        .HasForeignKey("IdCareer")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Career");
                });

            modelBuilder.Entity("SchoolManager.Models.preenrollment_infos", b =>
                {
                    b.HasOne("SchoolManager.Models.preenrollment_general", "preenrollment_general")
                        .WithMany()
                        .HasForeignKey("id_data")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("preenrollment_general");
                });

            modelBuilder.Entity("SchoolManager.Models.preenrollment_schools", b =>
                {
                    b.HasOne("SchoolManager.Models.preenrollment_general", "preenrollment_general")
                        .WithMany("Schools")
                        .HasForeignKey("id_data")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("preenrollment_general");
                });

            modelBuilder.Entity("SchoolManager.Models.preenrollment_tutors", b =>
                {
                    b.HasOne("SchoolManager.Models.preenrollment_general", "preenrollment_general")
                        .WithMany()
                        .HasForeignKey("id_data")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("preenrollment_general");
                });

            modelBuilder.Entity("SchoolManager.Models.preenrollment_careers", b =>
                {
                    b.Navigation("preenrollment_general");
                });

            modelBuilder.Entity("SchoolManager.Models.preenrollment_general", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Schools");
                });
#pragma warning restore 612, 618
        }
    }
}
