// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolManager.Data;

#nullable disable

namespace SchoolManager.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260130232455_ProceduresEntities")]
    partial class ProceduresEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchoolManager.Models.ProcedureAreas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Datetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ProcedureAreas");
                });

            modelBuilder.Entity("SchoolManager.Models.ProcedureDocuments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Datetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdProcedure")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("IdProcedure");

                    b.ToTable("ProcedureDocuments");
                });

            modelBuilder.Entity("SchoolManager.Models.ProcedureMonitoring", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Datetime")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdProcedure")
                        .HasColumnType("int");

                    b.Property<int>("IdStatus")
                        .HasColumnType("int");

                    b.Property<string>("IdUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdProcedure");

                    b.HasIndex("IdStatus");

                    b.ToTable("ProcedureMonitoring");
                });

            modelBuilder.Entity("SchoolManager.Models.ProcedureRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Datetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Folio")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("IdStatus")
                        .HasColumnType("int");

                    b.Property<int>("IdTypeProcedure")
                        .HasColumnType("int");

                    b.Property<string>("IdUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("IdStatus");

                    b.HasIndex("IdTypeProcedure");

                    b.ToTable("ProcedureRequest");
                });

            modelBuilder.Entity("SchoolManager.Models.ProcedureStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ProcedureStatus");
                });

            modelBuilder.Entity("SchoolManager.Models.ProcedureTypeDocuments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Datetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("ProcedureTypeDocuments");
                });

            modelBuilder.Entity("SchoolManager.Models.ProcedureTypeRequirements", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdTypeDocument")
                        .HasColumnType("int");

                    b.Property<int>("IdTypeProcedure")
                        .HasColumnType("int");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdTypeDocument");

                    b.HasIndex("IdTypeProcedure");

                    b.ToTable("ProcedureTypeRequirements");
                });

            modelBuilder.Entity("SchoolManager.Models.ProcedureTypes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Datetime")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdArea")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("IdArea");

                    b.ToTable("ProcedureTypes");
                });

            modelBuilder.Entity("SchoolManager.Models.ProcedureDocuments", b =>
                {
                    b.HasOne("SchoolManager.Models.ProcedureRequest", "ProcedureRequest")
                        .WithMany("ProcedureDocuments")
                        .HasForeignKey("IdProcedure")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcedureRequest");
                });

            modelBuilder.Entity("SchoolManager.Models.ProcedureMonitoring", b =>
                {
                    b.HasOne("SchoolManager.Models.ProcedureRequest", "ProcedureRequest")
                        .WithMany("ProcedureMonitorings")
                        .HasForeignKey("IdProcedure")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManager.Models.ProcedureStatus", "ProcedureStatus")
                        .WithMany()
                        .HasForeignKey("IdStatus")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProcedureRequest");

                    b.Navigation("ProcedureStatus");
                });

            modelBuilder.Entity("SchoolManager.Models.ProcedureRequest", b =>
                {
                    b.HasOne("SchoolManager.Models.ProcedureStatus", "ProcedureStatus")
                        .WithMany("ProcedureRequests")
                        .HasForeignKey("IdStatus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManager.Models.ProcedureTypes", "ProcedureType")
                        .WithMany("ProcedureRequests")
                        .HasForeignKey("IdTypeProcedure")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcedureStatus");

                    b.Navigation("ProcedureType");
                });

            modelBuilder.Entity("SchoolManager.Models.ProcedureTypeRequirements", b =>
                {
                    b.HasOne("SchoolManager.Models.ProcedureTypeDocuments", "ProcedureTypeDocument")
                        .WithMany("ProcedureTypeRequirements")
                        .HasForeignKey("IdTypeDocument")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManager.Models.ProcedureTypes", "ProcedureType")
                        .WithMany("Requirements")
                        .HasForeignKey("IdTypeProcedure")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcedureType");

                    b.Navigation("ProcedureTypeDocument");
                });

            modelBuilder.Entity("SchoolManager.Models.ProcedureTypes", b =>
                {
                    b.HasOne("SchoolManager.Models.ProcedureAreas", "ProcedureArea")
                        .WithMany("ProcedureTypes")
                        .HasForeignKey("IdArea")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcedureArea");
                });

            modelBuilder.Entity("SchoolManager.Models.ProcedureAreas", b =>
                {
                    b.Navigation("ProcedureTypes");
                });

            modelBuilder.Entity("SchoolManager.Models.ProcedureRequest", b =>
                {
                    b.Navigation("ProcedureDocuments");

                    b.Navigation("ProcedureMonitorings");
                });

            modelBuilder.Entity("SchoolManager.Models.ProcedureStatus", b =>
                {
                    b.Navigation("ProcedureRequests");
                });

            modelBuilder.Entity("SchoolManager.Models.ProcedureTypeDocuments", b =>
                {
                    b.Navigation("ProcedureTypeRequirements");
                });

            modelBuilder.Entity("SchoolManager.Models.ProcedureTypes", b =>
                {
                    b.Navigation("ProcedureRequests");

                    b.Navigation("Requirements");
                });
#pragma warning restore 612, 618
        }
    }
}
