// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolManager.Data;

#nullable disable

namespace SchoolManager.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchoolManager.Models.grades_extraordinary_grades", b =>
                {
                    b.Property<int>("ExtraordinaryGradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExtraordinaryGradeId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("FinalGradeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("ExtraordinaryGradeId");

                    b.HasIndex("FinalGradeId")
                        .IsUnique();

                    b.ToTable("grades_extraordinary_grades", (string)null);
                });

            modelBuilder.Entity("SchoolManager.Models.grades_final_grades", b =>
                {
                    b.Property<int>("FinalGradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FinalGradeId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<bool>("Passed")
                        .HasColumnType("bit");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("FinalGradeId");

                    b.HasIndex("GroupId");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("StudentId", "SubjectId", "GroupId");

                    b.ToTable("grades_final_grades", (string)null);
                });

            modelBuilder.Entity("SchoolManager.Models.grades_grade_level", b =>
                {
                    b.Property<int>("GradeLevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GradeLevelId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("GradeLevelId");

                    b.ToTable("grades_grade_level", (string)null);
                });

            modelBuilder.Entity("SchoolManager.Models.grades_grades", b =>
                {
                    b.Property<int>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GradeId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectUnitId")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("GradeId");

                    b.HasIndex("GroupId");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectUnitId");

                    b.HasIndex("StudentId", "SubjectUnitId", "GroupId");

                    b.ToTable("grades_grades", (string)null);
                });

            modelBuilder.Entity("SchoolManager.Models.grades_group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupId"));

                    b.Property<int>("GradeLevelId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SchoolCycleId")
                        .HasColumnType("int");

                    b.HasKey("GroupId");

                    b.HasIndex("GradeLevelId");

                    b.HasIndex("SchoolCycleId");

                    b.ToTable("grades_group", (string)null);
                });

            modelBuilder.Entity("SchoolManager.Models.grades_school_cycle", b =>
                {
                    b.Property<int>("SchoolCycleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SchoolCycleId"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("SchoolCycleId");

                    b.ToTable("grades_school_cycle", (string)null);
                });

            modelBuilder.Entity("SchoolManager.Models.grades_subject_unit", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnitId"));

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("UnitNumber")
                        .HasColumnType("int");

                    b.HasKey("UnitId");

                    b.HasIndex("SubjectId", "UnitNumber")
                        .IsUnique();

                    b.ToTable("grades_subject_unit", (string)null);
                });

            modelBuilder.Entity("SchoolManager.Models.grades_subjects", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectId"));

                    b.Property<int>("GradeLevelId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SubjectId");

                    b.HasIndex("GradeLevelId");

                    b.ToTable("grades_subjects", (string)null);
                });

            modelBuilder.Entity("SchoolManager.Models.grades_teacher_subject", b =>
                {
                    b.Property<int>("TeacherSubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherSubjectId"));

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("TeacherSubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("grades_teacher_subject", (string)null);
                });

            modelBuilder.Entity("SchoolManager.Models.grades_teacher_subject_group", b =>
                {
                    b.Property<int>("TeacherSubjectGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherSubjectGroupId"));

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherSubjectId")
                        .HasColumnType("int");

                    b.HasKey("TeacherSubjectGroupId");

                    b.HasIndex("GroupId");

                    b.HasIndex("TeacherSubjectId", "GroupId")
                        .IsUnique();

                    b.ToTable("grades_teacher_subject_group", (string)null);
                });

            modelBuilder.Entity("SchoolManager.Models.grades_unit_recovery", b =>
                {
                    b.Property<int>("UnitRecoveryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnitRecoveryId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("GradeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("UnitRecoveryId");

                    b.HasIndex("GradeId");

                    b.ToTable("grades_unit_recovery", (string)null);
                });

            modelBuilder.Entity("SchoolManager.Models.procedure_areas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("procedure_areas", (string)null);
                });

            modelBuilder.Entity("SchoolManager.Models.procedure_documents", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdProcedure")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("IdProcedure");

                    b.ToTable("procedure_documents", (string)null);
                });

            modelBuilder.Entity("SchoolManager.Models.procedure_monitoring", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdProcedure")
                        .HasColumnType("int");

                    b.Property<int>("IdStatus")
                        .HasColumnType("int");

                    b.Property<string>("IdUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdProcedure");

                    b.HasIndex("IdStatus");

                    b.ToTable("procedure_monitoring", (string)null);
                });

            modelBuilder.Entity("SchoolManager.Models.procedure_request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Folio")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("IdStatus")
                        .HasColumnType("int");

                    b.Property<int>("IdTypeProcedure")
                        .HasColumnType("int");

                    b.Property<string>("IdUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("IdStatus");

                    b.HasIndex("IdTypeProcedure");

                    b.ToTable("procedure_request", (string)null);
                });

            modelBuilder.Entity("SchoolManager.Models.procedure_status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StepOrder")
                        .HasColumnType("int");

                    b.Property<string>("TextColor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.HasKey("Id");

                    b.ToTable("procedure_status", (string)null);
                });

            modelBuilder.Entity("SchoolManager.Models.procedure_type_documents", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("procedure_type_documents", (string)null);
                });

            modelBuilder.Entity("SchoolManager.Models.procedure_type_requirements", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdTypeDocument")
                        .HasColumnType("int");

                    b.Property<int>("IdTypeProcedure")
                        .HasColumnType("int");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdTypeDocument");

                    b.HasIndex("IdTypeProcedure");

                    b.ToTable("procedure_type_requirements", (string)null);
                });

            modelBuilder.Entity("SchoolManager.Models.procedure_types", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdArea")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("IdArea");

                    b.ToTable("procedure_types", (string)null);
                });

            modelBuilder.Entity("SchoolManager.Models.grades_extraordinary_grades", b =>
                {
                    b.HasOne("SchoolManager.Models.grades_final_grades", "FinalGrade")
                        .WithOne("ExtraordinaryGrade")
                        .HasForeignKey("SchoolManager.Models.grades_extraordinary_grades", "FinalGradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FinalGrade");
                });

            modelBuilder.Entity("SchoolManager.Models.grades_final_grades", b =>
                {
                    b.HasOne("SchoolManager.Models.grades_group", "grades_group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolManager.Models.grades_subjects", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("grades_group");
                });

            modelBuilder.Entity("SchoolManager.Models.grades_grades", b =>
                {
                    b.HasOne("SchoolManager.Models.grades_group", "grades_group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolManager.Models.grades_subject_unit", "SubjectUnit")
                        .WithMany()
                        .HasForeignKey("SubjectUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SubjectUnit");

                    b.Navigation("grades_group");
                });

            modelBuilder.Entity("SchoolManager.Models.grades_group", b =>
                {
                    b.HasOne("SchoolManager.Models.grades_grade_level", "GradeLevel")
                        .WithMany("Groups")
                        .HasForeignKey("GradeLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolManager.Models.grades_school_cycle", "SchoolCycle")
                        .WithMany("Groups")
                        .HasForeignKey("SchoolCycleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GradeLevel");

                    b.Navigation("SchoolCycle");
                });

            modelBuilder.Entity("SchoolManager.Models.grades_subject_unit", b =>
                {
                    b.HasOne("SchoolManager.Models.grades_subjects", "Subject")
                        .WithMany("Units")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("SchoolManager.Models.grades_subjects", b =>
                {
                    b.HasOne("SchoolManager.Models.grades_grade_level", "GradeLevel")
                        .WithMany("Subjects")
                        .HasForeignKey("GradeLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GradeLevel");
                });

            modelBuilder.Entity("SchoolManager.Models.grades_teacher_subject", b =>
                {
                    b.HasOne("SchoolManager.Models.grades_subjects", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("SchoolManager.Models.grades_teacher_subject_group", b =>
                {
                    b.HasOne("SchoolManager.Models.grades_group", "grades_group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManager.Models.grades_teacher_subject", "TeacherSubject")
                        .WithMany()
                        .HasForeignKey("TeacherSubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeacherSubject");

                    b.Navigation("grades_group");
                });

            modelBuilder.Entity("SchoolManager.Models.grades_unit_recovery", b =>
                {
                    b.HasOne("SchoolManager.Models.grades_grades", "Grade")
                        .WithMany("Recoveries")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grade");
                });

            modelBuilder.Entity("SchoolManager.Models.procedure_documents", b =>
                {
                    b.HasOne("SchoolManager.Models.procedure_request", "ProcedureRequest")
                        .WithMany("ProcedureDocuments")
                        .HasForeignKey("IdProcedure")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcedureRequest");
                });

            modelBuilder.Entity("SchoolManager.Models.procedure_monitoring", b =>
                {
                    b.HasOne("SchoolManager.Models.procedure_request", "ProcedureRequest")
                        .WithMany("ProcedureMonitorings")
                        .HasForeignKey("IdProcedure")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManager.Models.procedure_status", "ProcedureStatus")
                        .WithMany()
                        .HasForeignKey("IdStatus")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProcedureRequest");

                    b.Navigation("ProcedureStatus");
                });

            modelBuilder.Entity("SchoolManager.Models.procedure_request", b =>
                {
                    b.HasOne("SchoolManager.Models.procedure_status", "ProcedureStatus")
                        .WithMany("ProcedureRequests")
                        .HasForeignKey("IdStatus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManager.Models.procedure_types", "ProcedureType")
                        .WithMany("ProcedureRequests")
                        .HasForeignKey("IdTypeProcedure")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcedureStatus");

                    b.Navigation("ProcedureType");
                });

            modelBuilder.Entity("SchoolManager.Models.procedure_type_requirements", b =>
                {
                    b.HasOne("SchoolManager.Models.procedure_type_documents", "ProcedureTypeDocument")
                        .WithMany("ProcedureTypeRequirements")
                        .HasForeignKey("IdTypeDocument")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManager.Models.procedure_types", "ProcedureType")
                        .WithMany("Requirements")
                        .HasForeignKey("IdTypeProcedure")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcedureType");

                    b.Navigation("ProcedureTypeDocument");
                });

            modelBuilder.Entity("SchoolManager.Models.procedure_types", b =>
                {
                    b.HasOne("SchoolManager.Models.procedure_areas", "ProcedureArea")
                        .WithMany("ProcedureTypes")
                        .HasForeignKey("IdArea")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcedureArea");
                });

            modelBuilder.Entity("SchoolManager.Models.grades_final_grades", b =>
                {
                    b.Navigation("ExtraordinaryGrade");
                });

            modelBuilder.Entity("SchoolManager.Models.grades_grade_level", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("SchoolManager.Models.grades_grades", b =>
                {
                    b.Navigation("Recoveries");
                });

            modelBuilder.Entity("SchoolManager.Models.grades_school_cycle", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("SchoolManager.Models.grades_subjects", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("SchoolManager.Models.procedure_areas", b =>
                {
                    b.Navigation("ProcedureTypes");
                });

            modelBuilder.Entity("SchoolManager.Models.procedure_request", b =>
                {
                    b.Navigation("ProcedureDocuments");

                    b.Navigation("ProcedureMonitorings");
                });

            modelBuilder.Entity("SchoolManager.Models.procedure_status", b =>
                {
                    b.Navigation("ProcedureRequests");
                });

            modelBuilder.Entity("SchoolManager.Models.procedure_type_documents", b =>
                {
                    b.Navigation("ProcedureTypeRequirements");
                });

            modelBuilder.Entity("SchoolManager.Models.procedure_types", b =>
                {
                    b.Navigation("ProcedureRequests");

                    b.Navigation("Requirements");
                });
#pragma warning restore 612, 618
        }
    }
}
